mutation DeleteRecipe($id: RecipeId!) {
  deleteRecipe(id: $id)
}

mutation DeleteVersion($recipeId: RecipeId!, $number: VersionNumber!) {
  deleteVersion(recipeId: $recipeId, number: $number)
}

mutation CopyVersion($recipeId: RecipeId!, $number: VersionNumber!, $title: RecipeTitle!) {
  copyVersion(recipeId: $recipeId, number: $number, title: $title) {
    id
  }
}

mutation UpdateRecipe($id: RecipeId!, $input: UpdateRecipeInput!) {
  updateRecipe(id: $id, input: $input) {
    id
    title
    category
  }
}

mutation UpdateWarnings($recipeId: RecipeId!, $warnings: [Warning!]!) {
  updateWarnings(recipeId: $recipeId, warnings: $warnings) {
    id
    warnings
  }
}

mutation UpdateRating($recipeId: RecipeId!, $versionNumber: VersionNumber!, $rating: Rating!) {
  updateRating(recipeId: $recipeId, versionNumber: $versionNumber, rating: $rating) {
    ...VersionFields
  }
}

mutation UpdateCoffeeParameters(
  $recipeId: RecipeId!
  $versionNumber: VersionNumber!
  $parameters: CoffeeParametersInput!
) {
  updateCoffeeParameters(
    recipeId: $recipeId
    versionNumber: $versionNumber
    parameters: $parameters
  ) {
    ...VersionFields
  }
}

mutation UpdateOvenProfile(
  $recipeId: RecipeId!
  $versionNumber: VersionNumber!
  $oven: OvenProfileInput
) {
  updateOvenProfile(recipeId: $recipeId, versionNumber: $versionNumber, oven: $oven) {
    number
  }
}

mutation UpdateComponent(
  $recipeId: RecipeId!
  $versionNumber: VersionNumber!
  $ingredient: Int!
  $component: RecipeId
) {
  updateComponent(
    recipeId: $recipeId
    versionNumber: $versionNumber
    ingredient: $ingredient
    component: $component
  ) {
    ...VersionFields
  }
}

mutation UpdateIngredients(
  $recipeId: RecipeId!
  $versionNumber: VersionNumber!
  $ingredients: [IngredientInput!]!
) {
  updateIngredients(recipeId: $recipeId, versionNumber: $versionNumber, ingredients: $ingredients) {
    number
  }
}
