mutation DeleteRecipe($id: RecipeId!) {
  deleteRecipe(id: $id)
}

mutation DeleteVersion($recipeId: RecipeId!, $number: VersionNumber!) {
  deleteVersion(recipeId: $recipeId, number: $number)
}

mutation UpdateRecipe($id: RecipeId!, $input: UpdateRecipeInput!) {
  updateRecipe(id: $id, input: $input) {
    id
    title
    category
  }
}

mutation UpdateWarnings($recipeId: RecipeId!, $warnings: [Warning!]!) {
  updateWarnings(recipeId: $recipeId, warnings: $warnings) {
    id
    warnings
  }
}

mutation UpdateRating($recipeId: RecipeId!, $versionNumber: VersionNumber!, $rating: Rating!) {
  updateRating(recipeId: $recipeId, versionNumber: $versionNumber, rating: $rating) {
    ...VersionFields
  }
}

mutation UpdateCoffeeParameters(
  $recipeId: RecipeId!
  $versionNumber: VersionNumber!
  $parameters: CoffeeParametersInput!
) {
  updateCoffeeParameters(
    recipeId: $recipeId
    versionNumber: $versionNumber
    parameters: $parameters
  ) {
    ...VersionFields
  }
}
