query Oven {
  oven {
    reachable
    remoteControlEnabled
    running {
      program
      temperature
      remaining
    }
    assistedProfiles {
      label
      program
      temperature
      duration
    }
  }
}

mutation StartOven($recipeId: RecipeId!, $version: VersionNumber!) {
  startOven(recipeId: $recipeId, version: $version) {
    reachable
    remoteControlEnabled
    running {
      program
      temperature
      remaining
    }
    assistedProfiles {
      label
      program
      temperature
      duration
    }
  }
}
